
name: Cataloging problems
description: Metadata issues that need to be fixed
body:
  - type: markdown
    attributes: 
      value: |
        Thank you for taking the time to report a cataloging problem. To address this issue, I need some information.
        ---
        
        Please be as complete as possible, as sometimes a lot of time passes before an issue can be addressed.
  - type: input
    id: date
    attributes:
      label: Date
      description: "Enter the date you found the issue."
      placeholder: "YYYY-MM-DD"
    validations:
      required: true  
  - type: input
    id: initials
    attributes:
      label: Your initials
      description: "Please leave your initials so that I can follow up with any further questions."
      placeholder: "e.g. LK"
    validations:
      required: true
  - type: input
    id: identifier
    attributes:
      label: Barcode
      description: "Please provide the barcode or other relevant identifier for the item."
      placeholder: "e.g. 36105226230189 or G3201.E4 1884.P6"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Issue type
      description: What kind of issue is it?
      options:
        - Call number
        - Barcode
        - Wrong storage location
        - Other
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might help me solve this problem.
    validations:
      required: true
      render: shell
