
name: Cataloging problems
description: Metadata issues that need to be fixed
body:
  - type: markdown
    attributes: 
      value: |
        Before opening a new issue, make sure this is not a duplicate.
        ---
        
        Thank you for taking the time to report a cataloging problem. To address this bug as fast as possible, I need some information.
  - type: input
    id: date
    attributes:
      label: Date
      description: "Enter the date you found the issue."
      placeholder: "YYYY-MM-DD"
    validations:
      required: true  
  - type: input
    id: initials
    attributes:
      label: Your initials
      description: "Please leave your initials so that I can follow up with any further questions."
      placeholder: "e.g. ECT"
    validations:
      required: true
  - type: input
    id: identifier
    attributes:
      label: Barcode
      description: "Please provide the barcode or other relevant identifier for the item."
      placeholder: "e.g. 123456789"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Issue type
      description: What kind of issue is it?
      options:
        - Call number mismatch
        - Duplicate call number
        - Wrong storage location
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might help me solve this problem.
    validations:
      required: true
      render: shell
